### PR TITLE
fix: GetMute package

### PR DESCRIPTION
**Pull request by ChristopheCVB**

### CODE REVIEW

**Comment by ChristopheCVB** [comment]
@TinaTiel Can you merge this please?

**Comment by TinaTiel** [comment]
I'll take a look later tonight

**Review by TinaTiel — CHANGES_REQUESTED** [review]
Looks good, only suggestion I have is to update the test to capture the getMute callback correctness. 

I've done this privately, but don't have permission to push to your remote -- so if you want to use this you're welcome to:
`ObsRemoteE2eObservationIT.java`
```
  @Test
  void setVolumeAndMute() {

    obsShould("Set the volume to 50% (note, appears 67% due to log scaling; check % in advanced audio properties)");
    remote.setSourceVisibility(null, "media", true, loggingCallback);
    remote.setVolume(SOURCE_MEDIA, 0.50, loggingCallback);
    obsShould("Mute the volume");
    remote.setMute(SOURCE_MEDIA, true, loggingCallback);
    remote.getMute(SOURCE_MEDIA, capturingCallback);
    waitReasonably();
    assertThat(getPreviousResponseAs(GetMuteResponse.class).isMuted()).isTrue();

    obsShould("Unmute the volume");
    remote.setMute(SOURCE_MEDIA, false, loggingCallback);
    remote.getMute(SOURCE_MEDIA, capturingCallback);
    waitReasonably();
    assertThat(getPreviousResponseAs(GetMuteResponse.class).isMuted()).isFalse();

    obsShould("Set the volume to 100%");
    remote.setVolume(SOURCE_MEDIA, 1.00, loggingCallback);

  }
```

**Review by TinaTiel — APPROVED** [review]
Thanks! Great work

**Pull request merged**
